In [39]:
import pandas as pd
import numpy as npy

print(f'EXERCISE 1:')
# Use pandas to create a Series named fruits from the following list:

fruits = ["kiwi", "mango", "strawberry", "pineapple", "gala apple", "honeycrisp apple", "tomato", 
          "watermelon", "honeydew", "kiwi", "kiwi", "kiwi", "mango", "blueberry", "blackberry", 
          "gooseberry", "papaya"]
fruits_series = pd.Series(fruits)

# Determine the number of elements in fruits.

print(f'# 1:')

num_elements = len(fruits_series)
print(num_elements)

print(fruits_series.shape)



# Output only the index from fruits.

print(f'# 2:') 
print(list(fruits_series.index))



# Output only the values from fruits.

print(f'# 3:')
print(fruits_series.values)

# Confirm the data type of the values in fruits.

print(f'# 4:')
print(fruits_series.dtype)

# Output only the first five values from fruits. Output the last three values. Output two random values from fruits.


print(f'# 5a: ')
print(fruits_series[:5])
print(fruits_series.head(5))

print(f'# 5b:')
print(fruits_series[-3:])
print(fruits_series.tail(3))

print(f'# 5c:')
print(fruits_series.sample(2))

# Run the .describe() on fruits to see what information it returns when called on a Series with string values.

print(f'# 6:')
print(fruits_series.describe())

# Run the code necessary to produce only the unique string values from fruits.

print(f'# 7:')

unique_fruits = pd.unique(fruits_series)

print(fruits_series.unique())

print(unique_fruits)

# Determine how many times each unique string value occurs in fruits.
print(f'#8:')

value_counts = fruits_series.value_counts()


print(value_counts)

# Determine the string value that occurs most frequently in fruits.

print(f'#9:')

most_common = fruits_series.value_counts().idxmax()

# print(fruits_series.value_counts().head(1))

print(fruits_series.value_counts().idxmax())
print(most_common)

# or 

print(value_counts.idxmax())

Determine the string value that occurs least frequently in fruits.

print(f'# 10:')

print(value_counts.idxmin())

EXERCISE 1:
# 1:
17
(17,)
# 2:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
# 3:
['kiwi' 'mango' 'strawberry' 'pineapple' 'gala apple' 'honeycrisp apple'
 'tomato' 'watermelon' 'honeydew' 'kiwi' 'kiwi' 'kiwi' 'mango' 'blueberry'
 'blackberry' 'gooseberry' 'papaya']
# 4:
object
# 5a:
0          kiwi
1         mango
2    strawberry
3     pineapple
4    gala apple
dtype: object
0          kiwi
1         mango
2    strawberry
3     pineapple
4    gala apple
dtype: object
# 5b:
14    blackberry
15    gooseberry
16        papaya
dtype: object
14    blackberry
15    gooseberry
16        papaya
dtype: object
# 5c:
5     honeycrisp apple
16              papaya
dtype: object
# 6:
count       17
unique      13
top       kiwi
freq         4
dtype: object
# 7:
['kiwi' 'mango' 'strawberry' 'pineapple' 'gala apple' 'honeycrisp apple'
 'tomato' 'watermelon' 'honeydew' 'blueberry' 'blackberry' 'gooseberry'
 'papaya']
['kiwi' 'mango' 'strawberry' 'pineapple' 'gala apple' 'honeycrisp apple'
 'tomato' 'watermelon' 'honeydew' 'blueberry' 'blackberry' 'gooseberry'
 'papaya']
#8:
kiwi                4
mango               2
strawberry          1
pineapple           1
gala apple          1
honeycrisp apple    1
tomato              1
watermelon          1
honeydew            1
blueberry           1
blackberry          1
gooseberry          1
papaya              1
Name: count, dtype: int64
#9:
kiwi
kiwi
kiwi
# 10:
strawberry

In [47]:
# EXERCISE 2

# Capitalize all the string values in fruits.

print(f'#9:')
print(fruits_series.str.capitalize())


# Count the letter "a" in all the string values (use string vectorization).
print(f'#2:')
print(fruits_series.str.count("a")) 

# Output the number of vowels in each and every string value.

print(f'#3:')

vowels = '[aeiouy]'

print(fruits_series.str.count(vowels))

# Write the code to get the longest string value from fruits.
print(f'#4')
index_of_longest_fruit = fruits_series.str.len().idxmax()

longest_fruit = fruits_series[index_of_longest_fruit]

print(index_of_longest_fruit, longest_fruit)

# Write the code to get the string values with 5 or more letters in the name.

print(f'#5')
five_plus_letters = fruits_series[fruits_series.str.len() >= 5]
print(five_plus_letters)

# Find the fruit(s) containing the letter "o" two or more times.

print(f'#6')
two_plus_os = fruits_series[fruits_series.str.count('o') >= 2]

print(two_plus_os)

# Write the code to get only the string values containing the substring "berry".

print(f'#7')

has_berry = fruits_series[fruits_series.str.contains("berry")]

print(has_berry)

# Write the code to get only the string values containing the substring "apple".

print(f'#8')

has_apple = fruits_series[fruits_series.str.contains("apple")]
fruits_series.str.contains("apple")

print(has_apple)

# Which string value contains the most vowels?

print(f'#9')
vowels_count = fruits_series.str.count(vowels)
most_vowels_count = vowels_count.idxmax()
word_most_vowels = fruits_series[most_vowels_count]
                               

print(word_most_vowels)

#9:
0                 Kiwi
1                Mango
2           Strawberry
3            Pineapple
4           Gala apple
5     Honeycrisp apple
6               Tomato
7           Watermelon
8             Honeydew
9                 Kiwi
10                Kiwi
11                Kiwi
12               Mango
13           Blueberry
14          Blackberry
15          Gooseberry
16              Papaya
dtype: object
#2:
0     0
1     1
2     1
3     1
4     3
5     1
6     1
7     1
8     0
9     0
10    0
11    0
12    1
13    0
14    1
15    0
16    3
dtype: int64
#3:
0     2
1     2
2     3
3     4
4     4
5     6
6     3
7     4
8     4
9     2
10    2
11    2
12    2
13    4
14    3
15    5
16    4
dtype: int64
#4
5 honeycrisp apple
#5
1                mango
2           strawberry
3            pineapple
4           gala apple
5     honeycrisp apple
6               tomato
7           watermelon
8             honeydew
12               mango
13           blueberry
14          blackberry
15          gooseberry
16              papaya
dtype: object
#6
6         tomato
15    gooseberry
dtype: object
#7
2     strawberry
13     blueberry
14    blackberry
15    gooseberry
dtype: object
#8
3           pineapple
4          gala apple
5    honeycrisp apple
dtype: object
#10
honeycrisp apple

In [56]:
# Use pandas to create a Series named letters from the following string. The easiest way to make this string into a Pandas series is to use list to convert each individual letter into a single string on a basic Python list.

import pandas as pd

# Which letter occurs the most frequently in the letters Series?


letter = pd.Series(list("hnvidduckkqxwymbimkccexbkmqygkxoyndmcxnwqarhyffsjpsrabtjzsypmzadfavyrnndndvswreauxovncx\
                        twzpwejilzjrmmbbgbyxvjtewqthafnbkqplarokkyydtubbmnexoypulzwfhqvckdpqtpoppzqrmcvhhpwgjwupgz\
                        hiofohawytlsiyecuproguy"))

print(letters.idxmax())

# Which letter occurs the Least frequently?

# How many vowels are in the Series?

# How many consonants are in the Series?

# Create a Series that has all of the same letters but uppercased.

# Create a bar plot of the frequencies of the 6 most commonly occuring letters.

AttributeError: 'str' object has no attribute 'idxmax'

In [46]:
# Use pandas to create a Series named numbers from the following list:

# ['$796,459.41', '$278.60', '$482,571.67', '$4,503,915.98', '$2,121,418.3', '$1,260,813.3', '$87,231.01', '$1,509,175.45', '$4,138,548.00', '$2,848,913.80', '$594,715.39', '$4,789,988.17', '$4,513,644.5', '$3,191,059.97', '$1,758,712.24', '$4,338,283.54', '$4,738,303.38', '$2,791,759.67', '$769,681.94', '$452,650.23']

# What is the data type of the numbers Series?

# How many elements are in the number Series?

# Perform the necessary manipulations by accessing Series attributes and methods to convert the numbers Series to a numeric data type.

# Run the code to discover the maximum value from the Series.

# Run the code to discover the minimum value from the Series.

# What is the range of the values in the Series?

# Bin the data into 4 equally sized intervals or bins and output how many values fall into each bin.

# Plot the binned data in a meaningful way. Be sure to include a title and axis labels.

# Use pandas to create a Series named exam_scores from the following list:

In [ ]:
# [60, 86, 75, 62, 93, 71, 60, 83, 95, 78, 65, 72, 69, 81, 96, 80, 85, 92, 82, 78]

# How many elements are in the exam_scores Series?

# Run the code to discover the minimum, the maximum, the mean, and the median scores for the exam_scores Series.

# Plot the Series in a meaningful way and make sure your chart has a title and axis labels.

# Write the code necessary to implement a curve for your exam_grades Series and save this as curved_grades. Add the necessary points to the highest grade to make it 100, and add the same number of points to every other score in the Series as well.

# Use a method to convert each of the numeric values in the curved_grades Series into a categorical value of letter grades. For example, 86 should be a 'B' and 95 should be an 'A'. Save this as a Series named letter_grades.

# Plot your new categorical letter_grades Series in a meaninful way and include a title and axis labels.